apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rafay-splunk.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "rafay-splunk.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rafay-splunk.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rafay-splunk.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: RELEASE
            value: {{ .Release.Name }}
          - name: NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: splunk-config
            mountPath: /config
          - name: auditlogs-config
            mountPath: /audit
          - name: kubectllogs-config
            mountPath: /kubectl
          - name: kubectllogs-cli-config
            mountPath: /kubectlcli
          - name: opalogs-config 
            mountPath: /opa
          - name: admissionlogs-config 
            mountPath: /admission
      volumes:
        - name: splunk-config
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: auditlogs-config
          configMap:
            name: {{ .Release.Name }}-auditlogs-ts-configmap
        - name: kubectllogs-config
          configMap:
            name: {{ .Release.Name }}-kubectllogs-ts-configmap
        - name: kubectllogs-cli-config
          configMap:
            name: {{ .Release.Name }}-kubectllogs-cli-ts-configmap
        - name: opalogs-config
          configMap:
            name: {{ .Release.Name }}-opalogs-ts-configmap
        - name: admissionlogs-config
          configMap:
            name: {{ .Release.Name }}-admissionlogs-ts-configmap
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
